menu:
- {name: 'EXPERIENCE', url: '/cv'}
- {name: 'INTERESTS', url: '/interests'}
- {name: 'COURSEWORK', url: '/courses'}
- {name: 'CONTACT', url: '/contact'}

interests:
  - name: 'Music'
    description: 'As the President & Singer of Cornell REAL A Cappella, I have a passionate involvement in music, particularly in performing KPOP song covers.'
  - name: 'Journalism'
    description: 'Drawing from my experience as the Chief Editor of my high school newspaper, I have a deep interest in journalism and written expression.'
  - name: 'Languages'
    description: 'I pride myself on being multilingual. I am proficient in English, speak Chinese natively, and have intermediate skills in Korean.'
  - name: 'Computer Skills'
    description: 'My technical skills are vast, ranging from programming in Python, C++, and SQL, to statistical analysis in R and Excel, to creative endeavors using STATA, CANVA, Logic Pro, Adobe Audition, and iMovie.'


courses:
- {name: 'ORIE 5270:Computational Methods in Operations Research'}
- {name: 'NBA 5420: Investment and Portfolio Management'}
- {name: 'ORIE 5370: Supply Chain Management'}
- {name: 'AEM 2210: Financial Accounting'}
- {name: 'STSCI 4740: Data Mining & Machine Learning'}
- {name: 'STSCI 4520: Statistical Computing'}
- {name: 'More Courses'}

social:
- {icon: 'github', link: 'https://github.com/yunnnnnnnz'}
- {icon: 'instagram', link: 'https://instagram.com/yunnnnnnnz'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yun-zhang-cornell-university/'}

contacts:
- {name: 'Yun Zhang', title: 'Cornell University Undergraduate and Master Student', department: 'Operations Research and Information Engineering', institution: 'Cornell University', phone: '(984) 261-5630', email: 'yz2847@cornell.edu', image: 'assets/img/contact.jpg'}
